volatile boolean hacking_in_progress = true;
volatile byte code[8] = {CHAR_b, CHAR_A, CHAR_A, CHAR_d, CHAR_A, CHAR_5, CHAR_5, CHAR_5};
volatile short delay_timer = 300;
volatile byte times_to_disp = 2;
byte repeat = 0;
byte display_iter = 0;
byte char_iter = 48;
short current_delay = 0;
unsigned long previous_milis = 0;